English translations, partial players view restyling and resolved #33 Order players by name
the-software-factory/angular-darts-tournament pull request #108
Opened 2017-06-01 17:26 UTC by Agomik

Put the "Plus" button at the end of shown players and ordered them by name.
I also translated in English some Italian text.

2017-06-05 08:18 UTC, astronati requested changes

2017-06-05 08:18 UTC, astronati commented on src/app/components/show-players/show-players.view.html
> +</div>
Ogni riga deve finire con un `\n` per considerarsi tale. Ti allego questa domanda su stackoverflow che puo essere un'interessante lettura.
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2017-06-05 08:18 UTC, astronati commented on src/app/components/show-players/show-players.component.js
> +function ShowPlayersController($element, SavedPlayers, SelectedPlayers, PlayersFactory) {
Per la definizione di un componente ti suggerirei il seguente approccio come gia fatto per gli altri file:
- definizione in un file
- template file esterno
- controller file esterno

2017-06-05 08:18 UTC, astronati commented on src/app/modules/home/home.view.html
> +      play
La traduzione in inglese fatta in questo modo non migliora in alcun modo l'applicazione. L'internazionalizzazione delle applicazioni prevede l'uso di token e di un servizio atto a intercettare la lingua usata dall'utente.

2017-06-05 08:18 UTC, astronati commented on src/app/modules/players/players.controller.js
> -      /**
Perche hai rimosso questi caratteri?

2017-06-05 08:18 UTC, astronati commented on src/app/modules/players/players.controller.js
> +  ]);
Vedi commento sopra

2017-06-05 08:18 UTC, astronati commented on src/app/modules/players/players.controller.spec.js
> +//  var createCtrl;
Perche hai commentato il codice in questo modo? Immagino che non funzionava piu.
Qualche idea su come fixarlo piuttosto che commentarlo?

2017-06-05 08:18 UTC, astronati commented on src/app/modules/players/players.view.html
> +      You have selected {{ vm.selectedPlayers.getAll().length }} player{{ vm.selectedPlayers.getAll().length != 1 ? "s" : "" }}
Uno dei tanti errori della traduzione in questo modo è che non permette di gestire il seguente caso:
- ITA `[n] giocatori sono stati selezionati`
- EN `You have selected [n] players`

Come risolveresti questo problema?

2017-06-05 08:20 UTC, astronati commented on src/app/components/show-players/show-players.component.js
> +  .component('showPlayers', {
Qual è stata la scelta che ti ha fatto spostare tutta questa logica dal controller a questo component?
Poteva essere fatta in un modo migliore? Un componente che si chiama `showPlayers` fa esattamente cio che ti aspetti faccia?

2017-06-05 08:20 UTC, astronati commented on src/app/components/show-players/show-players.view.html
> +        ng-repeat="player in $ctrl.savedPlayers.getAll() | orderBy: 'name' as ordered_players track by player.id"
Non usiamo lo snake_case per le variabili ma il camelCase

2017-06-06 07:52 UTC, Agomik commented on src/app/components/show-players/show-players.view.html
> +</div>
Ho passato una vita a cancellare i \n che mette Gedit a fine file...interessante :)

2017-06-06 08:33 UTC, Agomik commented on src/app/modules/players/players.view.html
> +      You have selected {{ vm.selectedPlayers.getAll().length }} player{{ vm.selectedPlayers.getAll().length != 1 ? "s" : "" }}
Considerando l'esistenza di un service per la traduzione direi di richiedere la stringa tramite una funzione che abbia come parametro il numero dei giocatori.
Come alternativa, attenendomi alla traduzione scelta (quindi senza fare "Players: [n]" :) ), ci potrebbe essere anche la delegazione al service della traduzione di leggere il numero dei giocatori selezionati ma non piace molto che il servizio di traduzione dipenda da selectedPlayers.

2017-06-06 09:58 UTC, Agomik commented on src/app/modules/home/home.view.html
> +      play
È meglio se uso per questo un servizio fatto da me o posso usare anche librerie come angular-translate?

2017-08-08 07:49 UTC, closed without merging