Resolved #68 Implement the 'cancel' button in the round page
the-software-factory/angular-darts-tournament pull request #111
Opened 2017-08-07 16:29 UTC by mevex

2017-08-07 20:30 UTC, astronati requested changes

2017-08-07 20:30 UTC, astronati commented on src/app/modules/round/round.controller.js
> +        return {angular.isNumber(vm.getShot(index)) && vm.getShot(index) != 0};
eslint è stato runnato?

2017-08-07 20:30 UTC, astronati commented on src/app/modules/round/round.controller.js
> +        return {angular.isNumber(vm.getShot(index)) && vm.getShot(index) != 0};
come mai hai aggiunto questo controllo in piu?

2017-08-07 20:30 UTC, astronati commented on src/app/modules/round/round.controller.js
> +        vm.shots[vm.shotIndex] -= vm.number;
Sembra che questo metodo funzioni solo in un caso. Se sei al terzo tiro e vuoi annullare tutti i tiri, questo metodo te lo permette?

2017-08-07 20:30 UTC, astronati commented on src/app/modules/round/round.controller.js
> +        if(!vm.getShot(vm.shotIndex)){
Cosa vuoi fare con questo metodo? eslint è stato eseguito?

2017-08-07 20:30 UTC, astronati commented on src/app/modules/round/round.view.html
> +        ng-disabled="!vm.isButtonTapped() || vm.isRoundCompleted()"
Perche metterci anche `isRoundCompleted`?

2017-08-09 08:57 UTC, astronati commented on src/app/modules/round/round.view.html
> +      <span class="glyphicon glyphicon-arrow-left"></span>
Usa `glyphicons-undo`

2017-08-09 08:58 UTC, astronati commented on src/app/modules/round/round.controller.js
>        function cancel() {
Rinominerei il metodo in `undo`

2017-08-09 09:01 UTC, astronati requested changes

2017-08-09 09:01 UTC, astronati commented on src/app/modules/round/round.controller.js
> +        vm.shots.length --;
Questo è validato da eslint?

2017-08-09 09:01 UTC, astronati commented on src/app/modules/round/round.controller.js
> +          vm.shots[vm.shotIndex] = null;
In entrambi i casi setti `vm.shots[vm.shotIndex] = null;`. Pensi ci sia un modo migliore di scriverlo?

2017-08-09 09:01 UTC, astronati commented on src/app/modules/round/round.controller.js
> +        if (!vm.shots[vm.shotIndex]) {
Cosa vuoi cercare con questa condizione?

2017-08-09 09:01 UTC, astronati commented on src/app/modules/round/round.controller.js
> +          vm.shotIndex --;
Questo è validato da eslint?

2017-08-09 14:06 UTC, mevex commented on src/app/modules/round/round.view.html
> +      <span class="glyphicon glyphicon-arrow-left"></span>
A quanto pare non esiste l'icona 'undo'

2017-08-10 16:10 UTC, astronati commented on src/app/modules/round/round.controller.js
> +        vm.shots.length --;
Perche hai bisogno di fare questo?

2017-08-10 16:11 UTC, astronati commented on src/app/modules/round/round.controller.js
> +        vm.shots[vm.shotIndex] = null;
Non ti conviene rimuovere proprio l elemento in posizione 'n' anziche metterlo a null?

2017-08-10 16:18 UTC, mevex commented on src/app/modules/round/round.controller.js
> +        vm.shots[vm.shotIndex] = null;
Usando il metodo 'splice' ?

2017-08-10 16:24 UTC, mevex commented on src/app/modules/round/round.controller.js
> +        vm.shots[vm.shotIndex] = null;
ok, fatto

2017-08-16 15:59 UTC, astronati approved these changes

2017-08-16 16:00 UTC, merged